language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
env:
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11
    - DJANGO=master
matrix:
    allow_failures:
        - env: DJANGO=1.11
        - env: DJANGO=master
install:
    - pip install tox-travis
script:
    - tox
