# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_event_log', '0002_auto_20180911_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_name',
            field=models.CharField(help_text='Appears as the Reporting Agent', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='outcome',
            field=models.CharField(choices=[('http://purl.org/NET/UNTL/vocabularies/eventOutcomes/#success', 'Success'), ('http://purl.org/NET/UNTL/vocabularies/eventOutcomes/#failure', 'Failure')], max_length=80),
        ),
    ]
